Update
AhmerovDmitry/StudyRepo pull request #5
Opened 2020-05-26 17:09 UTC by AhmerovDmitry

1. Additional logic
2. Information of persons is not repeated
3. Additional property to indicate the full name
4. More readable code

2020-05-26 20:17 UTC, AktuBuct requested changes

2020-05-26 20:17 UTC, AktuBuct commented on HW6/HW6/Models/Person.swift
> +        personFirstName + " " + personSecondName
```suggestion
        [personFirstName, personSecondName].joined(separator: " ")
```

2020-05-26 20:17 UTC, AktuBuct commented on HW6/HW6/Models/Person.swift
> +    var personFirstName: String
тут и так понятно, что это свойства объекта person, можно опустить это уточнение в свойствах. иначе потом страдное обращение будет типа person.personName, хотя person.name выглядит горзадо логичнее

2020-05-26 20:17 UTC, AktuBuct commented on HW6/HW6/Models/Person.swift
> +    static func addPerson() -> [Person] {
addPerson значит добавить одну персону. У тебя же возвращается массив персон, поэтому логичнее назвать что-то вроде randomList

2020-05-26 20:17 UTC, AktuBuct commented on HW6/HW6/Models/Person.swift
> +let name = ["Дмитрий", "Олег", "Андрей", "Александр", "Антон"]
все эти переменные попали в глобальный скопу и видны из всего приложения, хотя это что-то внутреннее. Логичнее это убрать внутрь и закрыть приватной областью видимости. по хорошему вообще конструкция типа такой:
```swift
private extension Person {
    enum Constants {
        static let name = ["Дмитрий", "Олег", "Андрей", "Александр", "Антон"]
        static let secondName = ["Ахмеров", "Русских", "Уваров", "Нихаев", "Сунгуров"]
        и т.д.
    }
}
```

Внутри используется enum потому что у него нет дефолтного инициализатора и объект такого класса нельзя создать. Поэтому ты пользуешься только статическими свойствами этого объекта констант

2020-05-26 20:17 UTC, AktuBuct commented on HW6/HW6/Controllers/TableViewController.swift
> +            let detailVC = segue.destination as! DetailViewController
ну тут лучше не анрапить а точно так же сделать optional binding через запятую в ифе выше.

2020-05-26 20:17 UTC, AktuBuct commented on HW6/HW6/Controllers/TableViewController.swift
> +        if let indexPath = tableView.indexPathForSelectedRow {
классно, замечательно, но я бы на твоем месте воспользовался методом делегата таблицы, который вызывается во время выделения ячейки`didSelectCell atIndexPath`. Плюс имеет смысл снимать выделение с выделенной ячейки при переходе, чтоб при возврате на экран эта ячейка не была подсвечена. `deselectRow atIndex animated`

2020-05-26 20:17 UTC, AktuBuct commented on HW6/HW6/Models/Person.swift
> +                                personPhone: phones[index])
если хоть один из этих четырех массивов массивов будет короче, чем массив names, у тебя будет краш. Лучше делать это как-то более безопасно.

2020-05-28 07:35 UTC, merged

2020-05-28 07:47 UTC, AhmerovDmitry reviewed
123